import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { Card, ProgressBar, SectionTitle, StatusPill } from '../components/ui';
import { ChoiceRow, FormField, FormModal } from '../components/FormModal';
import type { AuthSession } from '../services/auth.client';
import {
  createFinanceMovement, createProject, createPurchase, createTeamUser, getActivity, getContacts, getFinance, getProducts, getProjects, getPurchases, getTeam,
  setPurchaseStatus, updateProject, updateTeamUser,
  type ActivityRecord, type ContactRecord, type FinanceData, type ProductRecord, type ProjectRecord, type PurchaseRecord, type TeamUser
} from '../services/erp.client';
import { colors, radius, spacing } from '../theme';
import { Feedback, messageFrom, MiniButton, money, ScreenHeading, shortDate, screenStyles } from './shared';

const statusLabel = { draft: 'Borrador', ordered: 'Ordenada', received: 'Recibida', cancelled: 'Cancelada', planned: 'Planeado', active: 'Activo', completed: 'Completado', paused: 'Pausado' } as const;

function ModuleFeedback({ loading, error }: { loading: boolean; error: string }) {
  return <Feedback loading={loading} error={error} />;
}

export function PurchasesScreen({ session }: { session: AuthSession }) {
  const [items, setItems] = useState<PurchaseRecord[]>([]);
  const [suppliers, setSuppliers] = useState<ContactRecord[]>([]);
  const [products, setProducts] = useState<ProductRecord[]>([]);
  const [visible, setVisible] = useState(false);
  const [supplierId, setSupplierId] = useState('');
  const [productId, setProductId] = useState('');
  const [productQuery, setProductQuery] = useState('');
  const [quantity, setQuantity] = useState('1');
  const [unitCost, setUnitCost] = useState('0');
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [modalError, setModalError] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { const [purchases, contacts, catalog] = await Promise.all([getPurchases(session), getContacts(session), getProducts(session)]); setItems(purchases); setSuppliers(contacts.filter((item) => item.type === 'Proveedor')); setProducts(catalog); } catch (cause) { setError(messageFrom(cause)); } finally { setLoading(false); } }, [session]);
  useEffect(() => { void load(); }, [load]);
  const productOptions = products.filter((item) => `${item.name} ${item.sku}`.toLowerCase().includes(productQuery.toLowerCase())).slice(0, 20);
  async function save() { const qty = Number(quantity); const cost = Number(unitCost); if (!supplierId || !productId || !Number.isFinite(qty) || qty <= 0 || !Number.isFinite(cost) || cost < 0) { setModalError('Selecciona proveedor, producto, cantidad y costo válidos.'); return; } setBusy(true); setModalError(''); try { await createPurchase(session, { supplierId, items: [{ productId, quantity: qty, unitCost: cost }] }); setVisible(false); await load(); } catch (cause) { setModalError(messageFrom(cause)); } finally { setBusy(false); } }
  async function changeStatus(id: string, status: 'ordered' | 'received' | 'cancelled') { setError(''); try { await setPurchaseStatus(session, id, status); await load(); } catch (cause) { setError(messageFrom(cause)); } }
  return <><ScrollView contentContainerStyle={screenStyles.content} showsVerticalScrollIndicator={false}>
    <ScreenHeading eyebrow="ABASTECIMIENTO" title="Compras" subtitle="Crea órdenes a proveedores y recibe mercancía directamente en inventario." action="Nueva orden" onAction={() => { setVisible(true); setModalError(''); }} />
    <ModuleFeedback loading={loading} error={error} />
    <View style={screenStyles.grid}><Card style={styles.metric}><Text style={styles.metricValue}>{items.length}</Text><Text style={styles.metricLabel}>Órdenes registradas</Text></Card><Card style={styles.metric}><Text style={styles.metricValue}>{money(items.filter((item) => item.status !== 'cancelled').reduce((sum, item) => sum + item.total, 0))}</Text><Text style={styles.metricLabel}>Monto comprometido</Text></Card></View>
    <Card><SectionTitle title="Órdenes de compra" action={`${items.length} registros`} />{!loading && items.length === 0 ? <Feedback empty="Aún no hay órdenes de compra." /> : items.map((item, index) => <View key={item.id} style={[screenStyles.row, index === items.length - 1 && screenStyles.rowLast]}><View style={styles.moduleIcon}><Text style={styles.moduleIconText}>▣</Text></View><View style={screenStyles.rowCopy}><Text style={screenStyles.rowTitle}>{item.number}</Text><Text style={screenStyles.rowDetail}>{item.supplier.name} · {item.items.length} partidas · {shortDate(item.createdAt)}</Text></View><View><Text style={screenStyles.value}>{money(item.total)}</Text><StatusPill label={statusLabel[item.status]} tone={item.status === 'received' ? 'success' : item.status === 'cancelled' ? 'danger' : 'warning'} /></View><View style={screenStyles.actions}>{item.status === 'draft' ? <MiniButton label="Ordenar" onPress={() => void changeStatus(item.id, 'ordered')} /> : null}{item.status === 'ordered' ? <MiniButton label="Recibir" tone="success" onPress={() => void changeStatus(item.id, 'received')} /> : null}{!['received', 'cancelled'].includes(item.status) ? <MiniButton label="Cancelar" tone="danger" onPress={() => void changeStatus(item.id, 'cancelled')} /> : null}</View></View>)}</Card>
  </ScrollView><FormModal visible={visible} title="Nueva orden de compra" description="Al marcarla como recibida aumentará automáticamente el inventario." busy={busy} error={modalError} onClose={() => setVisible(false)} onSubmit={() => void save()}>
    <Text style={styles.fieldLabel}>Proveedor</Text><View style={styles.choiceList}>{suppliers.slice(0, 30).map((item) => <ChoiceButton key={item.id} active={supplierId === item.id} label={item.name} onPress={() => setSupplierId(item.id)} />)}</View>{suppliers.length === 0 ? <Text style={styles.help}>Crea primero un contacto de tipo Proveedor.</Text> : null}
    <FormField label="Buscar producto" value={productQuery} onChangeText={setProductQuery} placeholder="Nombre o SKU" /><View style={styles.choiceList}>{productOptions.map((item) => <ChoiceButton key={item.id} active={productId === item.id} label={`${item.name} · ${item.sku}`} onPress={() => { setProductId(item.id); setUnitCost(String(item.costo)); }} />)}</View>
    <FormField label="Cantidad" keyboardType="number-pad" value={quantity} onChangeText={setQuantity} /><FormField label="Costo unitario" keyboardType="decimal-pad" value={unitCost} onChangeText={setUnitCost} />
  </FormModal></>;
}

export function FinanceScreen({ session }: { session: AuthSession }) {
  const [data, setData] = useState<FinanceData | null>(null); const [visible, setVisible] = useState(false); const [type, setType] = useState<'income' | 'expense'>('expense'); const [category, setCategory] = useState('Operación'); const [concept, setConcept] = useState(''); const [amount, setAmount] = useState('');
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [modalError, setModalError] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { setData(await getFinance(session)); } catch (cause) { setError(messageFrom(cause)); } finally { setLoading(false); } }, [session]); useEffect(() => { void load(); }, [load]);
  async function save() { const value = Number(amount); if (concept.trim().length < 3 || category.trim().length < 2 || !Number.isFinite(value) || value <= 0) { setModalError('Completa concepto, categoría y un monto mayor a cero.'); return; } setBusy(true); setModalError(''); try { await createFinanceMovement(session, { type, category, concept, amount: value, occurredAt: new Date().toISOString() }); setVisible(false); setConcept(''); setAmount(''); await load(); } catch (cause) { setModalError(messageFrom(cause)); } finally { setBusy(false); } }
  return <><ScrollView contentContainerStyle={screenStyles.content} showsVerticalScrollIndicator={false}><ScreenHeading eyebrow="TESORERÍA" title="Finanzas" subtitle="Controla entradas, salidas y el saldo operativo de la empresa." action="Registrar movimiento" onAction={() => { setVisible(true); setModalError(''); }} /><ModuleFeedback loading={loading} error={error} />
    <View style={screenStyles.grid}><Metric label="Ingresos" value={money(data?.summary.income ?? 0)} tone="success" /><Metric label="Gastos" value={money(data?.summary.expense ?? 0)} tone="danger" /><Metric label="Saldo" value={money(data?.summary.balance ?? 0)} tone="info" /></View>
    <Card><SectionTitle title="Movimientos recientes" />{data?.items.length === 0 ? <Feedback empty="Registra el primer movimiento financiero." /> : data?.items.map((item, index) => <View key={item.id} style={[screenStyles.row, index === data.items.length - 1 && screenStyles.rowLast]}><View style={[styles.moduleIcon, item.type === 'income' ? styles.iconSuccess : styles.iconDanger]}><Text style={styles.moduleIconText}>{item.type === 'income' ? '↙' : '↗'}</Text></View><View style={screenStyles.rowCopy}><Text style={screenStyles.rowTitle}>{item.concept}</Text><Text style={screenStyles.rowDetail}>{item.category} · {shortDate(item.occurredAt)}</Text></View><Text style={[screenStyles.value, { color: item.type === 'income' ? colors.success : colors.danger }]}>{item.type === 'income' ? '+' : '−'}{money(item.amount)}</Text></View>)}</Card>
  </ScrollView><FormModal visible={visible} title="Movimiento financiero" busy={busy} error={modalError} onClose={() => setVisible(false)} onSubmit={() => void save()}><ChoiceRow label="Tipo" value={type} options={['income', 'expense'] as const} onChange={setType} /><FormField label="Categoría" value={category} onChangeText={setCategory} /><FormField label="Concepto" value={concept} onChangeText={setConcept} /><FormField label="Monto" keyboardType="decimal-pad" value={amount} onChangeText={setAmount} /></FormModal></>;
}

export function ProjectsScreen({ session }: { session: AuthSession }) {
  const [items, setItems] = useState<ProjectRecord[]>([]); const [visible, setVisible] = useState(false); const [form, setForm] = useState({ name: '', client: '', description: '', budget: '', dueAt: '' });
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [modalError, setModalError] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { setItems(await getProjects(session)); } catch (cause) { setError(messageFrom(cause)); } finally { setLoading(false); } }, [session]); useEffect(() => { void load(); }, [load]);
  async function save() { if (form.name.trim().length < 2) { setModalError('Escribe el nombre del proyecto.'); return; } setBusy(true); setModalError(''); try { await createProject(session, { name: form.name, client: form.client, description: form.description, budget: Number(form.budget) || 0, dueAt: form.dueAt || undefined, progress: 0, status: 'planned' }); setVisible(false); setForm({ name: '', client: '', description: '', budget: '', dueAt: '' }); await load(); } catch (cause) { setModalError(messageFrom(cause)); } finally { setBusy(false); } }
  async function advance(item: ProjectRecord) { const next = item.status === 'planned' ? { status: 'active' as const, progress: 25 } : item.status === 'active' ? { status: 'completed' as const, progress: 100 } : { status: 'active' as const, progress: Math.max(item.progress, 25) }; try { await updateProject(session, item.id, next); await load(); } catch (cause) { setError(messageFrom(cause)); } }
  return <><ScrollView contentContainerStyle={screenStyles.content} showsVerticalScrollIndicator={false}><ScreenHeading eyebrow="PLANEACIÓN" title="Proyectos" subtitle="Da seguimiento a iniciativas, presupuestos, avance y fechas objetivo." action="Nuevo proyecto" onAction={() => { setVisible(true); setModalError(''); }} /><ModuleFeedback loading={loading} error={error} /><View style={styles.projectGrid}>{items.map((item) => <Card key={item.id} style={styles.projectCard}><View style={styles.projectTop}><StatusPill label={statusLabel[item.status]} tone={item.status === 'completed' ? 'success' : item.status === 'paused' ? 'warning' : 'info'} /><Text style={styles.projectBudget}>{money(item.budget)}</Text></View><Text style={styles.projectName}>{item.name}</Text><Text style={styles.projectClient}>{item.client || 'Proyecto interno'}{item.dueAt ? ` · vence ${shortDate(item.dueAt)}` : ''}</Text><Text numberOfLines={2} style={styles.projectDescription}>{item.description || 'Sin descripción'}</Text><View style={styles.progressHeader}><Text style={styles.help}>Avance</Text><Text style={styles.progressValue}>{item.progress}%</Text></View><ProgressBar value={item.progress} /><View style={styles.projectActions}>{item.status !== 'completed' ? <MiniButton label={item.status === 'planned' ? 'Iniciar' : 'Completar'} tone="success" onPress={() => void advance(item)} /> : null}{item.status === 'active' ? <MiniButton label="Pausar" onPress={() => void updateProject(session, item.id, { status: 'paused' }).then(load)} /> : null}{item.status === 'paused' ? <MiniButton label="Reanudar" onPress={() => void advance(item)} /> : null}</View></Card>)}</View>{!loading && items.length === 0 ? <Feedback empty="Crea el primer proyecto para comenzar el seguimiento." /> : null}</ScrollView>
    <FormModal visible={visible} title="Nuevo proyecto" busy={busy} error={modalError} onClose={() => setVisible(false)} onSubmit={() => void save()}><FormField label="Nombre" value={form.name} onChangeText={(name) => setForm({ ...form, name })} /><FormField label="Cliente" value={form.client} onChangeText={(client) => setForm({ ...form, client })} /><FormField label="Descripción" multiline value={form.description} onChangeText={(description) => setForm({ ...form, description })} /><FormField label="Presupuesto" keyboardType="decimal-pad" value={form.budget} onChangeText={(budget) => setForm({ ...form, budget })} /><FormField label="Fecha objetivo (AAAA-MM-DD)" value={form.dueAt} onChangeText={(dueAt) => setForm({ ...form, dueAt })} /></FormModal></>;
}

export function TeamScreen({ session }: { session: AuthSession }) {
  const [items, setItems] = useState<TeamUser[]>([]); const [visible, setVisible] = useState(false); const [form, setForm] = useState({ name: '', email: '', password: '', role: 'sales' });
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [modalError, setModalError] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { setItems(await getTeam(session)); } catch (cause) { setError(messageFrom(cause)); } finally { setLoading(false); } }, [session]); useEffect(() => { void load(); }, [load]);
  async function save() { if (form.name.trim().length < 2 || !form.email.includes('@') || form.password.length < 10) { setModalError('Completa nombre, correo y una contraseña de al menos 10 caracteres.'); return; } setBusy(true); setModalError(''); try { await createTeamUser(session, form); setVisible(false); setForm({ name: '', email: '', password: '', role: 'sales' }); await load(); } catch (cause) { setModalError(messageFrom(cause)); } finally { setBusy(false); } }
  async function toggle(user: TeamUser) { try { await updateTeamUser(session, user.id, { isActive: !user.isActive }); await load(); } catch (cause) { setError(messageFrom(cause)); } }
  return <><ScrollView contentContainerStyle={screenStyles.content} showsVerticalScrollIndicator={false}><ScreenHeading eyebrow="ACCESO Y PERMISOS" title="Equipo" subtitle="Administra usuarios operativos, roles y acceso al ERP." action="Nuevo usuario" onAction={() => { setVisible(true); setModalError(''); }} /><ModuleFeedback loading={loading} error={error} /><Card><SectionTitle title="Usuarios" action={`${items.filter((item) => item.isActive).length} activos`} />{items.map((user, index) => <View key={user.id} style={[screenStyles.row, index === items.length - 1 && screenStyles.rowLast]}><View style={styles.avatar}><Text style={styles.avatarText}>{user.name.slice(0, 1).toUpperCase()}</Text></View><View style={screenStyles.rowCopy}><Text style={screenStyles.rowTitle}>{user.name}{user.id === session.user.id ? ' · Tú' : ''}</Text><Text style={screenStyles.rowDetail}>{user.email} · {user.roles.join(', ')}</Text></View><StatusPill label={user.isActive ? 'Activo' : 'Suspendido'} tone={user.isActive ? 'success' : 'danger'} />{user.id !== session.user.id ? <MiniButton label={user.isActive ? 'Suspender' : 'Activar'} tone={user.isActive ? 'danger' : 'success'} onPress={() => void toggle(user)} /> : null}</View>)}</Card></ScrollView>
    <FormModal visible={visible} title="Nuevo usuario" description="El usuario podrá iniciar sesión inmediatamente con la contraseña indicada." busy={busy} error={modalError} onClose={() => setVisible(false)} onSubmit={() => void save()}><FormField label="Nombre" value={form.name} onChangeText={(name) => setForm({ ...form, name })} /><FormField label="Correo" autoCapitalize="none" keyboardType="email-address" value={form.email} onChangeText={(email) => setForm({ ...form, email })} /><FormField label="Contraseña temporal" secureTextEntry value={form.password} onChangeText={(password) => setForm({ ...form, password })} /><ChoiceRow label="Rol" value={form.role} options={['sales', 'accounting', 'purchasing', 'projects', 'admin'] as const} onChange={(role) => setForm({ ...form, role })} /></FormModal></>;
}

export function ActivityScreen({ session }: { session: AuthSession }) {
  const [items, setItems] = useState<ActivityRecord[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { setItems(await getActivity(session)); } catch (cause) { setError(messageFrom(cause)); } finally { setLoading(false); } }, [session]); useEffect(() => { void load(); }, [load]);
  const successful = useMemo(() => items.filter((item) => item.statusCode < 400).length, [items]);
  return <ScrollView contentContainerStyle={screenStyles.content} showsVerticalScrollIndicator={false}><ScreenHeading eyebrow="AUDITORÍA" title="Actividad" subtitle="Consulta quién realizó cada cambio y si la operación fue aceptada." action="Actualizar" onAction={() => void load()} /><ModuleFeedback loading={loading} error={error} /><View style={screenStyles.grid}><Metric label="Eventos recientes" value={String(items.length)} tone="info" /><Metric label="Operaciones exitosas" value={String(successful)} tone="success" /></View><Card><SectionTitle title="Trazabilidad" />{!loading && items.length === 0 ? <Feedback empty="Todavía no hay actividad registrada." /> : items.map((item, index) => <View key={item.id} style={[screenStyles.row, index === items.length - 1 && screenStyles.rowLast]}><View style={styles.moduleIcon}><Text style={styles.moduleIconText}>{item.action === 'POST' ? '+' : item.action === 'DELETE' ? '−' : '↻'}</Text></View><View style={screenStyles.rowCopy}><Text style={screenStyles.rowTitle}>{item.userName} · {item.action}</Text><Text style={screenStyles.rowDetail}>{item.resource} · {new Date(item.timestamp).toLocaleString('es-MX')}</Text></View><StatusPill label={String(item.statusCode)} tone={item.statusCode < 400 ? 'success' : 'danger'} /></View>)}</Card></ScrollView>;
}

function ChoiceButton({ active, label, onPress }: { active: boolean; label: string; onPress: () => void }) { return <Pressable onPress={onPress} style={[styles.choice, active && styles.choiceActive]}><Text numberOfLines={1} style={[styles.choiceText, active && styles.choiceTextActive]}>{label}</Text></Pressable>; }
function Metric({ label, value, tone }: { label: string; value: string; tone: 'success' | 'danger' | 'info' }) { const color = tone === 'success' ? colors.success : tone === 'danger' ? colors.danger : colors.primaryBright; return <Card style={styles.metric}><Text style={[styles.metricValue, { color }]}>{value}</Text><Text style={styles.metricLabel}>{label}</Text></Card>; }

const styles = StyleSheet.create({
  metric: { flex: 1, minWidth: 190 }, metricValue: { color: colors.text, fontSize: 24, fontWeight: '900' }, metricLabel: { color: colors.textMuted, fontSize: 10, marginTop: 6 },
  moduleIcon: { width: 40, height: 40, borderRadius: 13, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.glow, borderWidth: 1, borderColor: colors.borderStrong }, moduleIconText: { color: colors.primaryBright, fontSize: 17, fontWeight: '900' }, iconSuccess: { backgroundColor: 'rgba(53,208,127,0.12)', borderColor: 'rgba(53,208,127,0.3)' }, iconDanger: { backgroundColor: 'rgba(255,90,107,0.12)', borderColor: 'rgba(255,90,107,0.3)' },
  fieldLabel: { color: colors.textMuted, fontSize: 11, fontWeight: '700' }, choiceList: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 }, choice: { maxWidth: '100%', paddingHorizontal: 11, paddingVertical: 8, borderRadius: radius.sm, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface }, choiceActive: { borderColor: colors.primaryBright, backgroundColor: colors.primaryDark }, choiceText: { maxWidth: 240, color: colors.textMuted, fontSize: 10, fontWeight: '700' }, choiceTextActive: { color: colors.text }, help: { color: colors.textMuted, fontSize: 10 },
  projectGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.md }, projectCard: { flex: 1, minWidth: 260, maxWidth: 370 }, projectTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 }, projectBudget: { color: colors.text, fontSize: 12, fontWeight: '800' }, projectName: { color: colors.text, fontSize: 17, fontWeight: '900', marginTop: 15 }, projectClient: { color: colors.primaryBright, fontSize: 10, fontWeight: '700', marginTop: 4 }, projectDescription: { minHeight: 34, color: colors.textMuted, fontSize: 10, lineHeight: 16, marginTop: 8 }, progressHeader: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 15, marginBottom: 7 }, progressValue: { color: colors.text, fontSize: 10, fontWeight: '800' }, projectActions: { flexDirection: 'row', flexWrap: 'wrap', gap: 7, marginTop: 14 },
  avatar: { width: 42, height: 42, borderRadius: 14, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.primaryDark, borderWidth: 1, borderColor: colors.borderStrong }, avatarText: { color: colors.text, fontSize: 16, fontWeight: '900' }
});
